config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root 'application#hello'
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles #, only: [:show,:index,:new,:create,:edit,:update,:destroy]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  # validates_presence_of :title
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  before_save {self.name=self.name.downcase}
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true,
                        uniqueness: {case_sensetive:false},
                        length: {minimum:3,maximum:25}

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save {self.email=email.downcase}
  validates :username,presence: true,
                        length: {minimum:3,maximum:25},
                        uniqueness: {case_sensetive:false}
EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,presence: true,
                        length: {maximum:105},
                        uniqueness: {case_sensetive:false},
                        format:{with:EMAIL_REGEX}
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def hello
    render html: 'Hello'
  end
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # @_request.reset_session
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:notice] ="You must be logged in for this action!"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #applies middleware before the actions specified in only
  before_action :set_article, only: [:show,:edit,:update,:destroy]
  before_action :require_user, except: [:show,:index]
  before_action :require_same_user, only: [:edit,:destroy,:update]
  def show
  end
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 8)

  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(get_article_data)
    @article.user=current_user
    if @article.save
      flash[:notice] = 'Article created!' # or :alert
      redirect_to article_path(@article)
    else
      flash[:notice] = 'Article was not created!' # or :alert
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(get_article_data)
      flash[:notice] = 'Article edited!' # or :alert
      redirect_to @article
    else
      flash[:notice] = 'Article was not created!' # or :alert
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  #makes definitions after private
  private

  def set_article
    @article = Article.find(params[:id])
  end

  def get_article_data
    params.require(:article).permit(:title, :description, category_ids: [])
  end
  
  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:notice] ="You must be the publisher to perform this action"
      redirect_to articles_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except:[:index,:show]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  def new 
    @category = Category.new
  end
  def create 
    @category=Category.new(get_category_params)
    if @category.save
      flash[:notice] ="category was successfully created"
      redirect_to @category
    else
      flash[:notice] ="category was not created"
      render 'new'
    end
  end

  def edit 
    @category = Category.find(params[:id])
  end
  def update 
    @category = Category.find(params[:id])
    if @category.update(get_category_params)
      flash[:notice] ="category was successfully updated"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def show 
    @category=Category.find(params[:id])
    @articles=@category.articles.paginate(page: params[:page], per_page:5)
  end
  private
    def get_category_params
      params.require(:category).permit(:name)
    end
    def require_admin
      if !(logged_in? && current_user.admin?)
        flash[:alert] ="you need to be an admin to performthis action"
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about; end
  # render html: "Hello World"
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
    render 'new'
  end

  def create 
    entered_params = get_user_params
    user=User.find_by(email:entered_params[:email])
    if user && user.authenticate(entered_params[:password])
      session[:user_id]=user.id
      flash.now[:notice] = 'Logged In Successfully' # or :alert
      redirect_to user
    else
      flash.now[:notice] = 'Incorrect Credentials!' # or :alert
      render "new"
    end
  end

  def destroy 
    session[:user_id]=nil
    flash[:notice] = 'Logged Out' #
    redirect_to root_path
  end


  private
  def get_user_params
    params.require(:session).permit(:password,:email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:show, :edit,:update,:destroy]
  before_action :require_user, only: [:edit,:update]
  before_action :require_same_user, only:[:edit,:update,:destroy]
  def new
    @user=User.new
  end
  
  def index
    @users = User.paginate(page: params[:page], per_page: 8)

  end
  def show
    @articles=@user.articles
  end

  def edit
  end
  def update
    if @user.update(get_user_params)
      flash[:notice] = 'User Updated!' # or :alert
      redirect_to @user
    else
      flash[:notice] = 'User was not updated!' # or :alert
      render "edit"
    end
  end
  def create
    @user=User.new(get_user_params)
    if @user.save
      flash[:notice] = 'User Created!' # or :alert
      redirect_to articles_path
    else
      flash.now[:notice] = 'User was not created!' # or :alert
      render "new"
    end
  end
  def destroy
    @user.destroy
    session[:user_id] = nil if current_user == @user
    flash[:notice] = 'User Deleted!' # or :alert
    redirect_to articles_path
  end
  private
  def get_user_params
    params.require(:user).permit(:username, :password,:email)
  end
  def get_user
    @user=User.find(params[:id])
  end
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:notice] ="You must be the profile owner to perform this action"
      redirect_to articles_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options={size:80})
    email=user.email.downcase
    hash = Digest::MD5.hexdigest(email)
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{options[:size]}"
    image_tag(image_src,alt:user.username)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_article.html.erb
<tr>
<td><%= link_to "By #{article.user.username}", user_path(article.user) %></td>
<td><%= article.title %></td>
<td><%= article.description %></td>
<% if article.categories.any? %>
  <%= render article.categories%>
<% end %>
<td><%= link_to 'Show', article_path(article) %></td>
<% if logged_in? && (current_user==article.user || current_user.admin?) %>
  <td><%= link_to 'Edit', edit_article_path(article) %></td>
  <td><%= link_to 'Delete', article_path(article), method: :delete , data: { confirm:"Are you sure?" } %></td>
<% end %>
</tr>

app/views/articles/_form.html.erb
<%= form_with(model:@article, local:true) do |f| %>

  <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </p>

  <p>
  <%= f.label :description %>
  <%= f.text_area :description %>
  </p>
  
  <p>
  <%= f.label :categories %>
  <%= f.collection_select(:category_ids, Category.all, :id, :name,
  {prompt: "Make selection"},{multiple: true}) %> 
  </p>
  
  <p>
  <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'shared/errors' ,obj:@article%>
<%= render 'form' %>
<%= link_to 'Cancel', articles_path %>

app/views/articles/index.html.erb
<h1>Showing Articles</h1>

<table style="margin:auto">
<thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th clospan="3">Actions</th>
  </tr>
</thead>
<tbody>

  <% @articles.each do |article| %>
    <%= render 'article', article: article %>
  <% end %>
</tbody>
</table>
</ul>
<div class="flickr_pagination" style="text-align:center;margin:auto">
    <%= will_paginate @articles %>
  </div>
<% if logged_in? %>
  <%= link_to "New Article", new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>Create New Article</h1>

<% if @article.errors.any? %>
  <h2>An error Occurred</h2>
  <% @article.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>
<%= render 'form' %>
<%= link_to 'Show Index', articles_path %>

app/views/articles/show.html.erb
<h1>Showing Article details</h1>
<% if @article.categories.any? %>
  <%= render @article.categories%>
<% end %>
<p><strong>Title:</strong><%=@article.title%></p>
<p><strong>Description:</strong><%=@article.description%></p>


<% if logged_in? && (current_user==@article.user || current_user.admin?) %>

  <%= link_to 'Edit', edit_article_path(@article) %>
  <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm:"Are you sure?" } %>
<% end %>
  <%= link_to 'Show Index', articles_path %>

app/views/categories/_category.html.erb
<tr>
<td><%= link_to "#{category.name}", category_path(category) %></td>

</tr>

app/views/categories/_form.html.erb
<%= form_with(model:@category, local:true) do |f| %>

  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>

  <p>
  <%= f.submit %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'shared/errors', obj:@category %>
<%= render 'form' %>
<%= link_to "[cancel and return to category page]", category_path(@category)%>

app/views/categories/index.html.erb
<h1>Showing Categories</h1>



<table style="margin:auto">
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>
  <tbody>
  
    <% @categories.each do |category| %>
      <%= render 'category', category: category %> 
          <tr>
    <td>
    <%= pluralize(category.articles.count,"article") %>
    </tr>
    <% end %>
  </tbody>
  </table>
  </ul>
  <div class="flickr_pagination" style="text-align:center;margin:auto">
      <%= will_paginate @categories %>
    </div>

app/views/categories/new.html.erb
<h1>Creating category</h1>

<%= render 'shared/errors', obj:@category %>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Showing Category</h1>
<p>name: <%= @category.name %></p>

<div style="text-align:center;width:100%;">
  <% if logged_in? && (current_user.admin?) %>
  <%= link_to "Edit Category Name", edit_category_path(@category) %>
  <%= link_to "Delete Category", category_path(@category) ,data: {"confirm":"Are you sure?" ,"turbo-method": :delete }%>
  <% end %>

  </div>
  <h1>Articles</h1>
  <table style="margin:auto">
<thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th clospan="3">Actions</th>
  </tr>
</thead>
<tbody>

  <% @articles.each do |article| %>
    <%= render 'articles/article', article: article %>

  <% end %>
  <%= will_paginate @articles, :container => false %>
</tbody>
</table>
</ul>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
<div style="text-align:center;margin:2rem auto">
<%= link_to 'home', root_path %>
<%= link_to 'Articles', articles_path %>
<% if logged_in? %>
<%= "Admin" if current_user.admin? %><%= link_to current_user.username, user_path(current_user) %>
<%= link_to 'Logout', logout_path, data: { "turbo-method": :delete } %>

<% else %>
<%= link_to 'SignUp', signup_path %>
<%= link_to 'Login', login_path %>

<% end %>
<%= link_to 'Categories', categories_path %>

<% if logged_in? && current_user.admin? %>
<%= link_to "Create Category", new_category_path %>
<% end %>

<%= link_to 'Users Index', users_path %>
<%= link_to 'About', about_path %>
</div>

  <div style="text-align:center;">
  <%= render 'layouts/messages' %>
  <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>
<%= link_to 'Show Index', articles_path %>
<%= link_to 'Root', root_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2>The Following Errors Occurred</h2>
  <ul>
  <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model:@user, local:true) do |f| %>
  
  <p>
  <%= f.label :username %>
  <%= f.text_field :username %>
  </p>

  <p>
  <%= f.label :email %>
  <%= f.text_field :email %>
  </p>
  <p>
  <%= f.label :password %>
  <%= f.text_field :password %>
  </p>
  
  <p>
  <%= f.submit(@user.new_record? ? "SignUp" : "Edit User") %>
  </p>
<% end %>

app/views/users/edit.html.erb
<div style="text-align:center;">
<h1>Edit User Account</h1>
<% if @user.errors.any? %>
<h2>An error Occurred</h2>
<% @user.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
  <% end %>
  <% end %>
  <%= render 'form' %>
  </div>

app/views/users/index.html.erb
<div style="text-align:center">
  <h1>Showing Users</h1>

  <% @users.each do |user| %>
  
  <div style="text-align:center;margin:2rem auto;">
  <%= link_to user.username, user %>
  <div style="display:block;text-align:center">
    <%= gravatar_for(user,size:180)%>
  </div>

  <%= pluralize(user.articles.count,"Article") %>
  <%= link_to 'Edit', edit_user_path(user) %>
  <% end %>
  </div>
<%= will_paginate @users %>
 
</div>

app/views/users/new.html.erb
<h1>New User Registration</h1>

<% if @user.errors.any? %>
  <h2>An error Occurred</h2>
  <% @user.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>
<%= render 'form' %>

app/views/users/show.html.erb
<div style="text-align:center;width:100%;">
  <h1>Showing User details</h1>
  <p><strong>Name:</strong><%=@user.username%></p>
  <p><strong>email:</strong><%=@user.email%></p>
  <div style="display:block">
  <%= gravatar_for @user, size:200 %>
  <% if logged_in? && (current_user==@user  || current_user.admin?) %>
  <%= link_to "Edit your profile", edit_user_path(@user) %>
  <%= link_to "Delete your profile", user_path(@user) ,data: {"confirm":"Are you sure?" ,"turbo-method": :delete }%>
  <% end %>

  </div>
  <h1>Articles</h1>
  <table style="margin:auto">
<thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th clospan="3">Actions</th>
  </tr>
</thead>
<tbody>

  <% @articles.each do |article| %>
    <%= render 'articles/article', article: article %>

  <% end %>
</tbody>
</table>
</ul>

  <%= link_to 'Edit', edit_user_path(@user) %>
  <%= link_to 'Show Index', users_path %>
</div>